'''
Sabiendo que ValueError es la excepción que se lanza cuando no podemos convertir
una cadena de texto en su valor numérico, escriba una función get_int() que lea 
un valor entero del usuario y lo devuelva, iterando mientras el valor no sea 
correcto. Intente resolver el ejercicio tanto de manera iterativa como recursiva.
'''
print ('@'*40,  'Inicio', '@'*40,'\n')
continuar= ('s')
while (continuar=='s' or continuar=='S'):




    continuar = input('Desea ejecutar de nuevo el programa pulse la tecla S y enter ')
print ('\n','#'*40,' FIN ', '#'*40)